# -*- coding: utf-8 -*-
"""Copy of Get started with Earth Engine for Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vm4_tunlZO9DtkqmHkFuT2g2u2Re0CU7

# Get started with Earth Engine for Python
"""

#@title Copyright 2024 The Earth Engine Community Authors { display-mode: "form" }
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""This quickstart will give you an interactive introduction to visualizing and
analyzing geospatial data with the Earth Engine Python interface.

## Before you begin

[Register or create](https://code.earthengine.google.com/register) a Google Cloud Project; you'll be prompted to complete the following steps. If you already have a project registered for Earth Engine access, skip to the next section.

  * Select the project's purpose: commercial or noncommercial.
  * If the purpose is noncommercial, select a project type.
  * Create a new Google Cloud project or select an existing project.
  * If the purpose is commercial, verify or set up billing for your project.
  * Confirm your project information.  

**Note:** If you don't plan to keep the resources that you create in this procedure, create a project instead of selecting an existing project. After you finish these steps, you can [delete the project](https://cloud.google.com/resource-manager/docs/creating-managing-projects#shutting_down_projects), removing all resources owned by the project.

## Notebook setup

**1.** Import the Earth Engine and geemap libraries.
"""

import ee
import geemap.core as geemap

import concurrent
import ee
import google
import io
import json
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import multiprocessing
import numpy as np
import requests
import tensorflow as tf

from google.api_core import retry
from google.colab import auth
from google.protobuf import json_format
from IPython.display import Image
from matplotlib import rc
from tqdm.notebook import tqdm

"""**2.** Authenticate and initialize the Earth Engine service. Follow the
resulting prompts to complete authentication. Be sure to replace PROJECT_ID
with the name of the project you set up for this quickstart.
"""

ee.Authenticate()
ee.Initialize(project='ee-ssc314159')

"""## Add raster data to a map

**1.** Load climate data for a given period and display its metadata.
"""

boundary = ee.FeatureCollection('users/ssc314159/Hirapur')
geometry = boundary.geometry()
output = 'jan2023images.gz'

@retry.Retry()
def get_patch(coords, asset_id, band):
  """Get a patch of pixels from an asset, centered on the coords."""
  point = ee.Geometry.Point(coords)
  request = {
    'fileFormat': 'NPY',
    'bandIds': [band],
    'region': point.buffer(1000).bounds().getInfo(),
    'assetId': asset_id
  }
  return np.load(io.BytesIO(ee.data.getPixels(request)))[band]


def _float_feature(floats):
  """Returns a float_list from a float list."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=floats))


def array_to_example(struct_array):
  """"Serialize a structured numpy array into a tf.Example proto."""
  struct_names = struct_array.dtype.names
  feature = {}
  shape = np.shape(struct_array[struct_names[0]])
  feature['h'] = _float_feature([shape[1]])
  feature['w'] = _float_feature([shape[2]])
  for f in struct_names:
    feature[f] = _float_feature(struct_array[f].flatten())
  return tf.train.Example(
      features = tf.train.Features(feature = feature))

jan_2023_climate = (
    ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED").select(['B4', 'B3', 'B2'])
    .filterDate('2013-01-05', '2023-01-30')
    .filter(ee.Filter.bounds(geometry))

)
jan_2023_climate

type(jan_2023_climate)

# Get a list of individual images
image_list = jan_2023_climate.toList(jan_2023_climate.size())

# Helper to download image thumbnails
def download_thumbnails():
    urls = []
    for i in range(image_list.size().getInfo()):
        image = ee.Image(image_list.get(i)).visualize(min=0, max=3000)
        url = image.getThumbURL({
            'region': geometry,
            'dimensions': 512,
            'format': 'jpg'
        })
        urls.append(url)
    return urls

urls = download_thumbnails()

urls

projection['crs']

projection = jan_2023_climate.select(['B5']).projection().getInfo()
task = ee.batch.Export.image.toDrive(
    image=jan_2023_climate,
    description='imageToDriveExample_transform',
    crs=projection['crs'],
    crsTransform=projection['transform'],
    region=geometry,
)
task.start()

executor = concurrent.futures.ThreadPoolExecutor(max_workers=200)

writer = tf.io.TFRecordWriter(output, 'GZIP')
future_to_image = {
    executor.submit(get_patch, image['id'], 'NDVI'):
        image['id'] for image in jan_2023_climate
}
arrays = ()
types = []
for future in concurrent.futures.as_completed(jan_2023_climate):
  image_id = jan_2023_climate[future]
  image_name = image_id.split('/')[-1]
  try:
      np_array = future.result()
      arrays += (np_array,)
      types.append((image_name, np.int_, np_array.shape))
  except Exception as e:
      print(e)
      pass
array = np.array([arrays], types)
example_proto = array_to_example(array)
writer.write(example_proto.SerializeToString())
writer.flush()

writer.close()

dir(jan_2023_climate)
downloadParams = {'name': 'jan_2023_climate', 'bands': ['B4', 'B5']}
jan_2023_climate.getDownloadURL(downloadParams)

"""**2.** Instantiate a map object and add the temperature band as a layer with
specific visualization properties. Display the map.
"""

m = geemap.Map(center=[24.1, 447.57], zoom=13)
m.add_layer(geometry)

m

"""## Add vector data to a map

**1.** Create a vector data object with points for three cities.
"""

cities = ee.FeatureCollection([
    ee.Feature(ee.Geometry.Point(10.75, 59.91), {'city': 'Oslo'}),
    ee.Feature(ee.Geometry.Point(-118.24, 34.05), {'city': 'Los Angeles'}),
    ee.Feature(ee.Geometry.Point(103.83, 1.33), {'city': 'Singapore'}),
])
cities

"""**2.** Add the city locations to the map and redisplay it."""

m.add_layer(cities, name='Cities')
m

"""## Extract and chart data

**1.** Import the Altair charting library.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q --upgrade altair
import altair as alt

"""**2.** Extract the climate data for the three cities as a pandas DataFrame."""

city_climates = jan_2023_climate.reduceRegions(cities, ee.Reducer.first())

city_climates_dataframe = ee.data.computeFeatures(
    {'expression': city_climates, 'fileFormat': 'PANDAS_DATAFRAME'}
)
city_climates_dataframe

"""**3.** Plot the temperature for the cities as a bar chart."""

alt.Chart(city_climates_dataframe).mark_bar(size=100).encode(
    alt.X('city:N', sort='y', axis=alt.Axis(labelAngle=0), title='City'),
    alt.Y('temperature_2m:Q', title='Temperature (K)'),
    tooltip=[
        alt.Tooltip('city:N', title='City'),
        alt.Tooltip('temperature_2m:Q', title='Temperature (K)'),
    ],
).properties(title='January 2023 temperature for selected cities', width=500)

"""## What's next

  * Learn about analyzing data with Earth Engine's [objects and methods](https://developers.google.com/earth-engine/guides/objects_methods_overview).
  * Learn about Earth Engine's [processing environments](https://developers.google.com/earth-engine/guides/processing_environments).
  * Learn about Earth Engine's [machine learning capabilities](https://developers.google.com/earth-engine/guides/machine-learning).
  * Learn how to [export your computation results to BigQuery](https://developers.google.com/earth-engine/guides/exporting_to_bigquery).
"""