
name: ml_harvest_env
channels:
  - conda-forge # Another popular channel with community-built packages
  - defaults
dependencies:
  - python=3.10
  - ipython
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - earthengine-api
  - pip: # Packages to install using pip
    - google-api-python-client
    - tqdm
    - opencv-python
    - geemap